apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-aws.com
subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: aws-operator
roleRef:
  kind: ClusterRole
  name: crd-aws.com
  apiGroup: rbac.authorization.k8s.io