apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: listprojects.devops.azure.com
spec:
  scope: Cluster
  group: devops.azure.com
  names: 
    kind: ListProject
    plural: listprojects
    shortNames: 
    - pts
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema: 
        type: object
        properties: 
          spec: 
            type: object
            properties:
              organizationName:
                type: string
              projectName: 
                type: string
              projectVisibility:
                type: string
              projectCreated:
                type: string
    additionalPrinterColumns:
    - name: Created
      type: string
      description: provides time when this project got update or created
      jsonPath: .spec.projectCreated
    - name: ID
      type: string
      description: provides pipeline id for a specific pipeline within a project
      jsonPath: .spec.projectVisibility
    - name: Name
      type: string
      description: provides the name of pipelines within a project
      jsonPath: .spec.projectName
    - name: Organization
      type: string
      description: Oganization were these pipelines, projects are located
      jsonPath: .spec.organizationName