apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: listpipelines.devops.azure.com
spec:
  scope: Cluster
  group: devops.azure.com
  names: 
    kind: ListPipeline
    plural: listpipelines
    shortNames:
      - "pl"
      - "pls"
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema: 
        type: object
        properties: 
          spec: 
            type: object
            properties:
              organizationName:
                type: string
              projectName:
                type: string
              pipelineName:
                type: string
              pipelineId: 
                type: integer
    additionalPrinterColumns:
    - name: Project
      type: string
      description: Total number of projects
      jsonPath: .spec.projectName
    - name: Organization
      type: string
      description: Organization were these pipelines, projects are located
      jsonPath: .spec.organizationName
    - name: Name
      type: string
      description: Name of the pipeline within a project
      jsonPath: .spec.pipelineName
    - name: Id
      type: integer
      description: Id of pipeline within a project
      jsonPath: .spec.pipelineId
