apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.devops.azure.com
spec:
  scope: Cluster
  group: devops.azure.com
  names: 
    kind: Project
    plural: projects
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema: 
        type: object
        properties: 
          spec: 
            type: object
            properties:
              organizationName:
                type: string
              projects:
                type: integer
    additionalPrinterColumns:
    - name: Projects
      type: integer
      description: Total number of projects
      jsonPath: .spec.projects
    - name: Organization
      type: string
      description: Organization were these pipelines, projects are located
      jsonPath: .spec.organizationName

