apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.devops.azure.com
spec:
  scope: Cluster
  group: devops.azure.com
  names: 
    kind: Pipeline
    plural: pipelines
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema: 
        type: object
        properties: 
          spec: 
            type: object
            properties:
              organizationName:
                type: string
              projectName:
                type: string
    additionalPrinterColumns:
    - name: Project
      type: string
      description: Total number of projects
      jsonPath: .spec.projectName
    - name: Organization
      type: string
      description: Organization were these pipelines, projects are located
      jsonPath: .spec.organizationName